trigger: none

variables:
- group: Sonar-Variables
- name: system.debug
  value: true


pool:
  name: Aarush_agent_pool

stages:
  - stage: Precommit
    displayName: Terraform_format_and_validate
    jobs:
      - job: A
        displayName: Terraform_Formatting_&_validation
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'myservconn'
            backendAzureRmOverrideSubscriptionID: 'b197523b-6a83-4a07-8922-3be74b9d39be'
            backendAzureRmResourceGroupName: 'TestRG'
            backendAzureRmStorageAccountName: 'testbackendsa'
            backendAzureRmContainerName: 'testsc'
            backendAzureRmKey: 'terraform20260717.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'custom'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'myservconn'
            environmentAzureRmOverrideSubscriptionID: 'b197523b-6a83-4a07-8922-3be74b9d39be'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'

  - stage: Quality_check
    displayName: tfsec_tflint
    jobs:
      - job: A
        displayName: Code_Quality_Check
        steps:
        - checkout: self
        - task: tfsec@1
          displayName: secret_scanning
          inputs:
            version: 'v1.26.0'
            dir: '.'

        - task: Bash@3
          displayName: Verfytflint
          continueOnError: true
          inputs:
            targetType: 'inline'
            script: |
              which tflint
              tflint --version
              tflint --init
              tflint

  - stage: Sonarqube
    displayName: Sonarqubecodequality
    jobs:
      - job: A
        displayName: CodequalitySQ
        steps:
        # - task: Bash@3
        #   inputs:
        #     targetType: 'inline'
        #     script: |
        #       echo "Build.SourceBranch=$(Build.SourceBranch)"
        #       echo "Build.SourceBranchName=$(Build.SourceBranchName)"
        
        # - task: SonarQubePrepare@8
        #   inputs:
        #     SonarQube: 'mysonarservconn'
        #     scannerMode: 'cli'
        #     cliScannerVersion: '7.2.0.5079'
        #     configMode: 'manual'
        #     cliProjectKey: 'terraform-infra'
        #     cliProjectName: 'Terraform Infrastructure'
        #     cliSources: '.'
        #     extraProperties: |
        #       sonar.scm.disabled=true

        - task: Bash@3
          displayName: Sonar Scan
          env:
            SONAR_HOST_URL: $(SONAR_HOST_URL)
            SONAR_TOKEN: $(SONAR_TOKEN)
          inputs:
            targetType: 'inline'
            script: |
              echo "Host : $SONAR_HOST_URL"
              sonar-scanner -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.token="$SONAR_TOKEN" -Dsonar.projectKey="terraform-infra" -Dsonar.projectName="Terraform Infrastructure" -Dsonar.sources=.

  # - stage: Infra_Planing
  # - stage: Revalidation
  # - stage: Artifacts_Store
  # - stage: cost_estimation_and_optimization
  # - stage: Deploy_to_Dev
  # - stage: Post_Deployment
  # - stage: Drift_Detection